server:
  port: 8080

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin123
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
